version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - public_data:/app/public
    command: npm run dev

volumes:
  node_modules:
  public_data:
